# Select image from https://hub.docker.com/_/php/
image: php:5.6

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install mysql driver
- docker-php-ext-install pdo_mysql

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install


# We test PHP5.6 (the default) with MySQL
test:
  script:
  - compose tests

# We test PHP7
test:php7:
  image: php:7
  script:
  - compose tests
  allow_failure: false
